### ISSUE TITLE
Upgrade phpBB

### ISSUE THREAD

**Issue by petercpg** [moztw/forum.moztw.org#5]
phpBB 3.0.13 security update 出了，此外 3.1.2 也 GA 一陣子了，可以考慮昇級。

我剛試著自己手動 patch 發現有一些檔案好像有 local modify 過不去，@appleboy 有空處理嗎？

**Comment by appleboy** [comment]
@petercpg 沒問題，這我來處理

**Comment by petercpg** [comment]
Thanks :+1:
